/* auto-generated by NAPI-RS */

export function convertSvgToReact(
  svgContent: string,
  componentName: string,
  isJavascript: boolean,
  destinationFolder: string
): Promise<string>;

export function validateSvg(content: string): boolean;